import functions_framework
from firebase_admin import credentials, messaging, initialize_app
from supabase import create_client, Client
import json
import os

# 1. Initialize Firebase Admin SDK
try:
    cred = credentials.Certificate(json.loads(os.environ.get('FIREBASE_CREDENTIALS')))
    initialize_app(credential=cred)
except ValueError:
    # Already initialized
    pass

# 2. Initialize Supabase Client
# These must be set in your Google Cloud Function Environment Variables
SUPABASE_URL = os.environ.get('SUPABASE_URL')
SUPABASE_KEY = os.environ.get('SUPABASE_SERVICE_KEY') 
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

@functions_framework.http
def send_push_notification(request):
    """
    Sends FCM push notification and persists it to Supabase.
    
    Expected JSON body:
    {
        "fcm_token": "device_token",
        "user_id": "supabase_user_uuid",
        "type": "video_processed",
        "title": "Notification Title",
        "body": "Notification Body",
        "metadata": {
            "locationId": "123",
            "locationName": "Beach Cafe"
        }
    }
    """
    
    # Handle CORS preflight
    if request.method == 'OPTIONS':
        headers = {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'POST',
            'Access-Control-Allow-Headers': 'Content-Type, Authorization',
            'Access-Control-Max-Age': '3600'
        }
        return ('', 204, headers)
    
    # CORS headers for actual request
    headers = {
        'Access-Control-Allow-Origin': '*',
        'Content-Type': 'application/json'
    }
    
    # 3. Verify Authorization
    auth_header = request.headers.get('Authorization', '')
    expected_token = os.environ.get('API_SECRET_KEY', '')
    
    if not auth_header.startswith('Bearer ') or auth_header[7:] != expected_token:
        return (json.dumps({'error': 'Unauthorized'}), 401, headers)
    
    if request.method != 'POST':
        return (json.dumps({'error': 'Method not allowed'}), 405, headers)
    
    try:
        request_json = request.get_json(silent=True)
        if not request_json:
            return (json.dumps({'error': 'Invalid JSON body'}), 400, headers)
        
        # 4. Extract and Validate Fields
        fcm_token = request_json.get('fcm_token')
        user_id = request_json.get('user_id')  # Required for DB persistence
        notif_type = request_json.get('type')  # Maps to Flutter NotificationType enum
        
        if not all([fcm_token, user_id, notif_type]):
            return (json.dumps({'error': 'Missing fcm_token, user_id, or type'}), 400, headers)
        
        title = request_json.get('title', 'New Notification')
        body = request_json.get('body', '')
        metadata = request_json.get('metadata', {}) # Subclass specific data (e.g. locationId)

        # 5. Persist to Supabase Database
        # We save this first to generate the unique notification_id
        db_record = {
            "user_id": user_id,
            "type": notif_type,
            "title": title,
            "message": body,
            "metadata": metadata,
            "is_read": False
        }
        
        db_response = supabase.table("notifications").insert(db_record).execute()
        
        if not db_response.data:
            raise Exception("Failed to insert notification into database")
            
        # Get the UUID generated by Supabase
        notification_id = db_response.data[0]['id']

        # 6. Prepare FCM Data Payload
        # We merge the DB ID and the metadata so Flutter can parse the subclass
        # All values MUST be strings for FCM data
        fcm_data = {
            "id": str(notification_id),
            "type": str(notif_type),
            "timestamp": db_response.data[0]['created_at']
        }
        
        # Flatten metadata into the top-level data object for the Flutter factory
        for key, value in metadata.items():
            fcm_data[key] = str(value)
        
        # 7. Build the FCM Message
        message = messaging.Message(
            notification=messaging.Notification(
                title=title,
                body=body,
            ),
            token=fcm_token,
            data=fcm_data,
            apns=messaging.APNSConfig(
                payload=messaging.APNSPayload(
                    aps=messaging.Aps(
                        sound='default',
                        badge=1,
                        content_available=True,
                    )
                )
            ),
            android=messaging.AndroidConfig(
                priority='high',
                notification=messaging.AndroidNotification(
                    sound='default',
                    priority='high',
                )
            )
        )
        
        # 8. Send the notification
        fcm_response = messaging.send(message)
        
        return (json.dumps({
            'success': True,
            'notification_id': str(notification_id),
            'fcm_message_id': fcm_response
        }), 200, headers)
        
    except ValueError as e:
        # Catches FCM-specific errors (invalid token, etc.)
        print(f"❌ FCM Error: {e}")
        return (json.dumps({'error': 'FCM error', 'details': str(e)}), 500, headers)
        
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        return (json.dumps({'error': 'Internal server error', 'details': str(e)}), 500, headers)