// project level gradle 
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    plugins.withType(org.jetbrains.kotlin.gradle.plugin.KotlinBasePlugin).configureEach {
        kotlin {
            jvmToolchain(17)
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")

    // tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    //     kotlinOptions.jvmTarget = "17"
    // }

    // tasks.withType(JavaCompile).configureEach {
    //     sourceCompatibility = JavaVersion.VERSION_17
    //     targetCompatibility = JavaVersion.VERSION_17
    // }

    // java {
    //     toolchain {
    //         languageVersion.set(JavaLanguageVersion.of(17))
    //     }
    // }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
