-- ============================================================================
-- Compact app analytics storage
-- ============================================================================
-- Goal:
--   - Keep existing analytics views
--   - Store only fields required by those views
--   - Keep only events used by those views
--   - Reduce retention window to lower storage pressure

DROP VIEW IF EXISTS public.analytics_daily_user_activity;
DROP VIEW IF EXISTS public.analytics_retention_cohorts;
DROP VIEW IF EXISTS public.analytics_feature_adoption_daily;
DROP VIEW IF EXISTS public.analytics_notification_funnel_daily;

CREATE TABLE IF NOT EXISTS public.app_analytics_events_v2 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    event_name TEXT NOT NULL,
    session_id TEXT NOT NULL,
    user_id UUID REFERENCES public.users (supabase_id) ON DELETE SET NULL,
    anon_id UUID,
    feature_name TEXT,
    properties JSONB,
    CONSTRAINT app_analytics_events_v2_event_name_snake_case_chk CHECK (
        event_name ~ '^[a-z][a-z0-9_]*$'
    ),
    CONSTRAINT app_analytics_events_v2_actor_presence_chk CHECK (
        user_id IS NOT NULL OR anon_id IS NOT NULL
    )
);

TRUNCATE TABLE public.app_analytics_events_v2;

INSERT INTO public.app_analytics_events_v2 (
    occurred_at,
    event_name,
    session_id,
    user_id,
    anon_id,
    feature_name,
    properties
)
SELECT
    occurred_at,
    event_name,
    session_id,
    user_id,
    anon_id,
    CASE
        WHEN event_name IN (
            'search_opened',
            'magic_search_submitted',
            'location_card_opened',
            'location_saved',
            'location_disliked',
            'collection_created',
            'bubble_opened'
        ) THEN COALESCE(NULLIF(feature_name, ''), event_name)
        ELSE NULL
    END AS feature_name,
    CASE
        WHEN event_name = 'notification_permission_result'
             AND properties IS NOT NULL
             AND COALESCE(properties->>'status', '') <> ''
        THEN jsonb_build_object('status', properties->>'status')
        ELSE NULL
    END AS properties
FROM public.app_analytics_events
WHERE occurred_at >= NOW() - INTERVAL '45 days'
  AND event_name IN (
      'session_started',
      'app_foregrounded',
      'session_ended',
      'screen_view',
      'tab_switched',
      'search_opened',
      'magic_search_submitted',
      'location_card_opened',
      'location_saved',
      'location_disliked',
      'collection_created',
      'bubble_opened',
      'notification_permission_prompted',
      'notification_permission_result',
      'notification_received',
      'notification_opened',
      'deep_link_routed',
      'deep_link_failed'
  );

DROP TABLE public.app_analytics_events;
ALTER TABLE public.app_analytics_events_v2 RENAME TO app_analytics_events;
ALTER SEQUENCE public.app_analytics_events_v2_id_seq RENAME TO app_analytics_events_id_seq;

CREATE INDEX IF NOT EXISTS idx_app_analytics_events_event_name_occurred_at
    ON public.app_analytics_events (event_name, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_analytics_events_occurred_at_desc
    ON public.app_analytics_events (occurred_at DESC);

ALTER TABLE public.app_analytics_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS app_analytics_events_no_read_anon
    ON public.app_analytics_events;
CREATE POLICY app_analytics_events_no_read_anon
    ON public.app_analytics_events
    FOR SELECT
    TO anon
    USING (false);

DROP POLICY IF EXISTS app_analytics_events_no_read_authenticated
    ON public.app_analytics_events;
CREATE POLICY app_analytics_events_no_read_authenticated
    ON public.app_analytics_events
    FOR SELECT
    TO authenticated
    USING (false);

DROP POLICY IF EXISTS app_analytics_events_no_insert_anon
    ON public.app_analytics_events;
CREATE POLICY app_analytics_events_no_insert_anon
    ON public.app_analytics_events
    FOR INSERT
    TO anon
    WITH CHECK (false);

DROP POLICY IF EXISTS app_analytics_events_no_insert_authenticated
    ON public.app_analytics_events;
CREATE POLICY app_analytics_events_no_insert_authenticated
    ON public.app_analytics_events
    FOR INSERT
    TO authenticated
    WITH CHECK (false);

DROP POLICY IF EXISTS app_analytics_events_no_update_anon
    ON public.app_analytics_events;
CREATE POLICY app_analytics_events_no_update_anon
    ON public.app_analytics_events
    FOR UPDATE
    TO anon
    USING (false)
    WITH CHECK (false);

DROP POLICY IF EXISTS app_analytics_events_no_update_authenticated
    ON public.app_analytics_events;
CREATE POLICY app_analytics_events_no_update_authenticated
    ON public.app_analytics_events
    FOR UPDATE
    TO authenticated
    USING (false)
    WITH CHECK (false);

DROP POLICY IF EXISTS app_analytics_events_no_delete_anon
    ON public.app_analytics_events;
CREATE POLICY app_analytics_events_no_delete_anon
    ON public.app_analytics_events
    FOR DELETE
    TO anon
    USING (false);

DROP POLICY IF EXISTS app_analytics_events_no_delete_authenticated
    ON public.app_analytics_events;
CREATE POLICY app_analytics_events_no_delete_authenticated
    ON public.app_analytics_events
    FOR DELETE
    TO authenticated
    USING (false);

REVOKE ALL ON TABLE public.app_analytics_events FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.app_analytics_events_id_seq FROM anon, authenticated;
GRANT SELECT ON TABLE public.app_analytics_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.app_analytics_events_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.track_app_event(
    p_event_name TEXT,
    p_event_category TEXT,
    p_session_id TEXT,
    p_anon_id UUID,
    p_screen_name TEXT,
    p_feature_name TEXT,
    p_duration_ms INT,
    p_occurred_at TIMESTAMPTZ,
    p_app_version TEXT,
    p_build_number TEXT,
    p_platform TEXT,
    p_os_version TEXT,
    p_locale TEXT,
    p_timezone TEXT,
    p_properties JSONB DEFAULT '{}'::JSONB
) RETURNS VOID AS $$
DECLARE
    v_user_id UUID := auth.uid();
    v_event_name TEXT := LOWER(TRIM(COALESCE(p_event_name, '')));
    v_session_id TEXT := TRIM(COALESCE(p_session_id, ''));
    v_feature_name TEXT := NULLIF(TRIM(COALESCE(p_feature_name, '')), '');
    v_properties JSONB := NULL;
BEGIN
    IF v_event_name = '' THEN
        RETURN;
    END IF;

    IF v_event_name !~ '^[a-z][a-z0-9_]*$' THEN
        RETURN;
    END IF;

    IF v_session_id = '' THEN
        RETURN;
    END IF;

    IF v_user_id IS NULL AND p_anon_id IS NULL THEN
        RETURN;
    END IF;

    IF v_event_name NOT IN (
        'session_started',
        'app_foregrounded',
        'session_ended',
        'screen_view',
        'tab_switched',
        'search_opened',
        'magic_search_submitted',
        'location_card_opened',
        'location_saved',
        'location_disliked',
        'collection_created',
        'bubble_opened',
        'notification_permission_prompted',
        'notification_permission_result',
        'notification_received',
        'notification_opened',
        'deep_link_routed',
        'deep_link_failed'
    ) THEN
        RETURN;
    END IF;

    IF v_event_name = 'notification_permission_result' THEN
        IF p_properties IS NOT NULL
           AND COALESCE(p_properties->>'status', '') <> '' THEN
            v_properties := jsonb_build_object(
                'status',
                p_properties->>'status'
            );
        END IF;
    END IF;

    IF v_event_name NOT IN (
        'search_opened',
        'magic_search_submitted',
        'location_card_opened',
        'location_saved',
        'location_disliked',
        'collection_created',
        'bubble_opened'
    ) THEN
        v_feature_name := NULL;
    END IF;

    INSERT INTO public.app_analytics_events (
        occurred_at,
        event_name,
        session_id,
        user_id,
        anon_id,
        feature_name,
        properties
    )
    VALUES (
        COALESCE(p_occurred_at, NOW()),
        v_event_name,
        v_session_id,
        v_user_id,
        p_anon_id,
        v_feature_name,
        v_properties
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.track_app_event(
    TEXT, TEXT, TEXT, UUID, TEXT, TEXT, INT, TIMESTAMPTZ, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.track_app_event(
    TEXT, TEXT, TEXT, UUID, TEXT, TEXT, INT, TIMESTAMPTZ, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, JSONB
) TO anon, authenticated, service_role;

CREATE OR REPLACE VIEW public.analytics_daily_user_activity AS
WITH activity AS (
    SELECT
        (occurred_at AT TIME ZONE 'UTC')::DATE AS activity_date,
        COALESCE(user_id::TEXT, anon_id::TEXT) AS actor_id,
        session_id
    FROM public.app_analytics_events
    WHERE event_name IN (
        'session_started',
        'app_foregrounded',
        'session_ended',
        'screen_view',
        'tab_switched',
        'search_opened',
        'magic_search_submitted',
        'location_saved',
        'location_disliked',
        'bubble_opened'
    )
),
daily AS (
    SELECT
        activity_date,
        COUNT(DISTINCT actor_id) AS dau,
        COUNT(DISTINCT session_id) AS total_sessions
    FROM activity
    GROUP BY activity_date
)
SELECT
    d.activity_date,
    d.dau,
    d.total_sessions,
    ROUND(d.total_sessions::NUMERIC / NULLIF(d.dau, 0), 3) AS sessions_per_active_user,
    (
        SELECT COUNT(DISTINCT a.actor_id)
        FROM activity a
        WHERE a.activity_date BETWEEN d.activity_date - 6 AND d.activity_date
    ) AS wau,
    (
        SELECT COUNT(DISTINCT a.actor_id)
        FROM activity a
        WHERE a.activity_date BETWEEN d.activity_date - 29 AND d.activity_date
    ) AS mau,
    ROUND(
        d.dau::NUMERIC / NULLIF((
            SELECT COUNT(DISTINCT a.actor_id)
            FROM activity a
            WHERE a.activity_date BETWEEN d.activity_date - 29 AND d.activity_date
        ), 0),
        4
    ) AS dau_mau_stickiness,
    ROUND(
        (
            SELECT AVG(user_days.days_active::NUMERIC)
            FROM (
                SELECT
                    a.actor_id,
                    COUNT(DISTINCT a.activity_date) AS days_active
                FROM activity a
                WHERE a.activity_date BETWEEN d.activity_date - 6 AND d.activity_date
                GROUP BY a.actor_id
            ) user_days
        ),
        3
    ) AS avg_active_days_per_user_7d
FROM daily d
ORDER BY d.activity_date DESC;

CREATE OR REPLACE VIEW public.analytics_retention_cohorts AS
WITH activity AS (
    SELECT DISTINCT
        COALESCE(user_id::TEXT, anon_id::TEXT) AS actor_id,
        (occurred_at AT TIME ZONE 'UTC')::DATE AS activity_date
    FROM public.app_analytics_events
    WHERE event_name IN ('session_started', 'app_foregrounded')
),
first_seen AS (
    SELECT
        actor_id,
        MIN(activity_date) AS cohort_date
    FROM activity
    GROUP BY actor_id
)
SELECT
    fs.cohort_date,
    COUNT(*) AS cohort_size,
    COUNT(*) FILTER (
        WHERE EXISTS (
            SELECT 1
            FROM activity a
            WHERE a.actor_id = fs.actor_id
              AND a.activity_date = fs.cohort_date + 1
        )
    ) AS d1_retained_users,
    COUNT(*) FILTER (
        WHERE EXISTS (
            SELECT 1
            FROM activity a
            WHERE a.actor_id = fs.actor_id
              AND a.activity_date = fs.cohort_date + 7
        )
    ) AS d7_retained_users,
    COUNT(*) FILTER (
        WHERE EXISTS (
            SELECT 1
            FROM activity a
            WHERE a.actor_id = fs.actor_id
              AND a.activity_date = fs.cohort_date + 30
        )
    ) AS d30_retained_users,
    ROUND(
        (COUNT(*) FILTER (
            WHERE EXISTS (
                SELECT 1
                FROM activity a
                WHERE a.actor_id = fs.actor_id
                  AND a.activity_date = fs.cohort_date + 1
            )
        ))::NUMERIC / NULLIF(COUNT(*), 0),
        4
    ) AS d1_retention_rate,
    ROUND(
        (COUNT(*) FILTER (
            WHERE EXISTS (
                SELECT 1
                FROM activity a
                WHERE a.actor_id = fs.actor_id
                  AND a.activity_date = fs.cohort_date + 7
            )
        ))::NUMERIC / NULLIF(COUNT(*), 0),
        4
    ) AS d7_retention_rate,
    ROUND(
        (COUNT(*) FILTER (
            WHERE EXISTS (
                SELECT 1
                FROM activity a
                WHERE a.actor_id = fs.actor_id
                  AND a.activity_date = fs.cohort_date + 30
            )
        ))::NUMERIC / NULLIF(COUNT(*), 0),
        4
    ) AS d30_retention_rate
FROM first_seen fs
GROUP BY fs.cohort_date
ORDER BY fs.cohort_date DESC;

CREATE OR REPLACE VIEW public.analytics_feature_adoption_daily AS
SELECT
    (occurred_at AT TIME ZONE 'UTC')::DATE AS activity_date,
    COALESCE(feature_name, event_name) AS feature_name,
    COUNT(*) AS event_count,
    COUNT(DISTINCT COALESCE(user_id::TEXT, anon_id::TEXT)) AS unique_users
FROM public.app_analytics_events
WHERE event_name IN (
    'search_opened',
    'magic_search_submitted',
    'location_card_opened',
    'location_saved',
    'location_disliked',
    'collection_created',
    'bubble_opened'
)
GROUP BY
    (occurred_at AT TIME ZONE 'UTC')::DATE,
    COALESCE(feature_name, event_name)
ORDER BY activity_date DESC, feature_name;

CREATE OR REPLACE VIEW public.analytics_notification_funnel_daily AS
WITH base AS (
    SELECT
        (occurred_at AT TIME ZONE 'UTC')::DATE AS activity_date,
        event_name,
        COALESCE(user_id::TEXT, anon_id::TEXT) AS actor_id,
        properties
    FROM public.app_analytics_events
    WHERE event_name IN (
        'notification_permission_prompted',
        'notification_permission_result',
        'notification_received',
        'notification_opened',
        'deep_link_routed',
        'deep_link_failed'
    )
)
SELECT
    activity_date,
    COUNT(*) FILTER (WHERE event_name = 'notification_permission_prompted') AS permission_prompted,
    COUNT(*) FILTER (
        WHERE event_name = 'notification_permission_result'
          AND COALESCE(properties->>'status', '') IN ('authorized', 'provisional')
    ) AS permission_enabled_events,
    COUNT(*) FILTER (WHERE event_name = 'notification_received') AS notifications_received,
    COUNT(*) FILTER (WHERE event_name = 'notification_opened') AS notifications_opened,
    COUNT(*) FILTER (WHERE event_name = 'deep_link_routed') AS deep_link_routed,
    COUNT(*) FILTER (WHERE event_name = 'deep_link_failed') AS deep_link_failed,
    COUNT(DISTINCT actor_id) FILTER (WHERE event_name = 'notification_received') AS users_received,
    COUNT(DISTINCT actor_id) FILTER (WHERE event_name = 'notification_opened') AS users_opened,
    ROUND(
        (COUNT(*) FILTER (WHERE event_name = 'notification_opened'))::NUMERIC
        / NULLIF(COUNT(*) FILTER (WHERE event_name = 'notification_received'), 0),
        4
    ) AS open_rate
FROM base
GROUP BY activity_date
ORDER BY activity_date DESC;

GRANT SELECT ON public.analytics_daily_user_activity TO service_role;
GRANT SELECT ON public.analytics_retention_cohorts TO service_role;
GRANT SELECT ON public.analytics_feature_adoption_daily TO service_role;
GRANT SELECT ON public.analytics_notification_funnel_daily TO service_role;

CREATE OR REPLACE FUNCTION public.cleanup_old_app_analytics_events(
    p_retention INTERVAL DEFAULT INTERVAL '45 days'
) RETURNS INTEGER AS $$
DECLARE
    v_deleted_count INTEGER;
BEGIN
    DELETE FROM public.app_analytics_events
    WHERE occurred_at < NOW() - p_retention;

    GET DIAGNOSTICS v_deleted_count = ROW_COUNT;
    RETURN v_deleted_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

REVOKE ALL ON FUNCTION public.cleanup_old_app_analytics_events(INTERVAL) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.cleanup_old_app_analytics_events(INTERVAL) TO service_role;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
        IF EXISTS (
            SELECT 1
            FROM cron.job
            WHERE jobname = 'cleanup_old_app_analytics_events_daily'
        ) THEN
            PERFORM cron.unschedule('cleanup_old_app_analytics_events_daily');
        END IF;

        PERFORM cron.schedule(
            'cleanup_old_app_analytics_events_daily',
            '15 3 * * *',
            $job$SELECT public.cleanup_old_app_analytics_events(INTERVAL '45 days');$job$
        );
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'pg_cron scheduling skipped: %', SQLERRM;
END;
$$;
