CREATE TABLE IF NOT EXISTS public.social_post_actions (
    social_post_action_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url text NOT NULL,
    normalized_url text GENERATED ALWAYS AS (
        lower(
            regexp_replace(
                CASE
                    WHEN btrim(url) ~* '^https?://' THEN
                        split_part(split_part(btrim(url), '#', 1), '?', 1)
                    ELSE
                        'https://' || split_part(split_part(btrim(url), '#', 1), '?', 1)
                END,
                '/+$',
                ''
            )
        )
    ) STORED,
    platform text NOT NULL,
    location_ids bigint[] NOT NULL DEFAULT '{}',
    eat_list_collection_id uuid NULL REFERENCES public.collections(collection_id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT social_post_actions_url_not_blank CHECK (btrim(url) <> ''),
    CONSTRAINT social_post_actions_platform_check CHECK (platform IN ('tiktok', 'instagram')),
    CONSTRAINT social_post_actions_has_action CHECK (
        cardinality(location_ids) > 0 OR eat_list_collection_id IS NOT NULL
    ),
    CONSTRAINT social_post_actions_location_ids_not_null CHECK (
        array_position(location_ids, NULL) IS NULL
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS social_post_actions_normalized_url_key
    ON public.social_post_actions(normalized_url);

CREATE INDEX IF NOT EXISTS social_post_actions_platform_idx
    ON public.social_post_actions(platform);

ALTER TABLE public.social_post_actions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.social_post_actions FROM anon, authenticated;
GRANT ALL ON TABLE public.social_post_actions TO service_role;
