-- Shared promo codes (e.g. FRESHER): ownerless referral codes, promo_reward
-- vouchers, rewards.promo_code_vouchers, voucher location/reusable columns and
-- the updated issue_referral_vouchers / accept_pending_referral_for_user /
-- redeem_voucher functions.
--
-- This schema was applied to production by hand before the 20261001000000
-- baseline was dumped, so the baseline already contains all of it. The original
-- statements are intentionally removed: re-running them on a fresh database
-- (supabase db reset, CI replay) fails with "already exists" errors. Production
-- history records this version as applied. Kept as a no-op to preserve the
-- local/remote version match.
SELECT 1;
