create table public.locations (
  location_id bigserial not null,
  name text not null,
  vicinity text null,
  lat numeric(9, 6) null,
  lng numeric(9, 6) null,
  created_at timestamp without time zone not null default now(),
  rating real null,
  user_ratings_total numeric null,
  price_level numeric null,
  photo_reference text null,
  saved_count smallint null,
  google_place_id text null,
  business_status text null,
  editorial_summary text null,
  website text null,
  international_phone_number text null,
  types text null,
  opening_hours_text text[] null,
  opening_hours_periods jsonb null,
  open_now boolean null,
  cuisine_primary text null,
  is_open_late boolean null,
  is_open_early boolean null,
  is_sunday_open boolean null,
  price_bucket text null,
  derived_attributes jsonb null,
  data_version text not null default 'v1'::text,
  ingested_at timestamp with time zone not null default now(),
  photo_reference_valid_until timestamp with time zone null,
  photo_reference_score text null,
  image_stored boolean null default false,
  emoji text null,
  updated_at timestamp with time zone null default (now() AT TIME ZONE 'utc'::text),
  google_maps_uri text null,
  photos jsonb null,
  reviews jsonb null,
  review_summary text null,
  good_for_children boolean null,
  good_for_groups boolean null,
  good_for_watching_sports boolean null,
  live_music boolean null,
  outdoor_seating boolean null,
  serves_beer boolean null,
  serves_breakfast boolean null,
  serves_brunch boolean null,
  serves_cocktails boolean null,
  serves_coffee boolean null,
  serves_dessert boolean null,
  serves_dinner boolean null,
  serves_lunch boolean null,
  serves_vegetarian_food boolean null,
  serves_wine boolean null,
  menu text null,
  generated_summary text null,
  reccomended_dishes text null,
  menu_analysis_confidence text null,
  geog geography null,
  vibe_vector real[] null,
  updated_vibe boolean null default false,
  is_takeaway boolean null,
  dietary_requirement_vector integer[] null,
  cuisine_scores_json jsonb null,
  constraint locations_pkey primary key (location_id)
) TABLESPACE pg_default;

create unique INDEX IF not exists idx_locations_google_place_id on public.locations using btree (google_place_id) TABLESPACE pg_default;

create index IF not exists idx_locations_geog on public.locations using gist (geog) TABLESPACE pg_default;

-- Partial index for unprocessed locations (most efficient for backfill queries)
create index IF not exists idx_locations_cuisine_primary_null on public.locations (location_id) where cuisine_primary is null TABLESPACE pg_default;

-- Regular index for general cuisine_primary queries
create index IF not exists idx_locations_cuisine_primary on public.locations using btree (cuisine_primary) TABLESPACE pg_default;